// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-eb7Kh60mbmfnnhYPNtOve3htPoYbW0Y',
    appId: '1:471522883420:web:dfd11740955f0e82123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    authDomain: 'admin-dashboard-2ea77.firebaseapp.com',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
    measurementId: 'G-R0TZ40KDRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgzj8MtnZrOjaTEyMoVoCVwdYW4sHUG_U',
    appId: '1:471522883420:android:a113cc2a3c22bccb123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFAdQNHaKopyxixWTAhRUJRf5veqzudqk',
    appId: '1:471522883420:ios:40844f3c08e6f939123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFAdQNHaKopyxixWTAhRUJRf5veqzudqk',
    appId: '1:471522883420:ios:40844f3c08e6f939123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-eb7Kh60mbmfnnhYPNtOve3htPoYbW0Y',
    appId: '1:471522883420:web:aace0e4a8b2d25ff123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    authDomain: 'admin-dashboard-2ea77.firebaseapp.com',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
    measurementId: 'G-ZZXVG6JTR6',
  );
}
